### ISSUE TITLE
Could you give a running example of code that reproduces the sensor results?

### ISSUE THREAD

**Issue by zb-520** [oezyurty/CLUDA#3]
Could you give a running example of code that reproduces the sensor results?

**Comment by oezyurty** [comment]
Hi, thanks again for your interest in our work! :) 

I have updated our README, I believe it will facilitate a more straight-forward usage. 

Specifically, you can find a new table explaining the purpose of each argument. Don't get confused by the length of table, each method-dataset pair uses nearly the half of these listed arguments. We just wanted to keep everything in one place, so that i) it is easier to automate experiments across methods and datasets, and ii) it is more convenient for a new user to find all necessary arguments in one place. 

I have also added the running examples of our CLUDA on each sensor dataset. Further, you can find a quick recipe of how to start testing other UDA methods. 

In the near future, I will add similar examples on how to run our code in healthcare dataset in more detail: across different age groups and across different health institutions. 

We highly appreciate your feedback for making our work more accessible!
