### ISSUE TITLE
tensor

### ISSUE THREAD

**Issue by MF-XU** [oezyurty/CLUDA#6]
Dear author, thank you for your excellent work, which is very inspiring to my work and very interested in your work. I have been reading your code recently, but I do not have MIme-IV data set, this data set needs to be applied for, but I have checked the application process on the Internet, and it takes a long time to apply for this data set. Therefore, I want to build a random tensor input into the network to debug this model, like the one in the figure below, so I would like to ask you what shape of the tensor sent into the network is, please kindly inform me if it is convenient.
![rad](https://github.com/oezyurty/CLUDA/assets/102813678/64e0b141-a4a6-4921-b2ab-7b07248d5224)

**Comment by oezyurty** [comment]
Hi, thank you so much for your kind words! I am so happy to see your interest in our work! 

I assume you are referring to MIMIC-IV dataset, as we used in our paper. Unfortunately, there is no direct answer to your question :( The reason is, the original dataset is in fact quite complex with its health measurements are distributed over 20+ tables. That's exactly why it requires certain pre-processing pipeline to get the final tensors. And for the final tensors, you can just shape them in any way that's useful for your final model. 

Although you don't have to exactly follow our approach, perhaps our [dataset class](https://github.com/oezyurty/CLUDA/blob/main/utils/dataset.py) can give you some idea. 

As another suggestion, maybe you can start with the sensor datasets instead, since they are easier to be acquired. Then for the MIMIC-IV dataset, you would only need to adjust the length, and num channels for the tensor dimensions. 

Hope this information would be helpful to you. Best of luck with your research!
