### ISSUE TITLE
Performance result question

### ISSUE THREAD

**Issue by helloxueen** [oezyurty/CLUDA#9]
I used my own dataset in cluda, when source and target keep the same, the result is OK, the src performance and trg performance can smoothly rise. 
But when trg dataset is changed in cluda, cdan, advskm, homm, mmda, vrada, the src performance is OK, but the trg performance can not rise. But using other method I wanna know why? I checked the domain loss code, it seems no problm.

**Comment by oezyurty** [comment]
Hi, thanks for your message! 

It seems like the issue is related to the data, not to the models, given that many models fail to improve the performance on the target domain. 

Just to ensure the models are working fine, you can try to run some existing datasets and observe the performance. 

If they are working as expected on these datasets, I suspect that in your dataset, the source and target domains don't share much information from which UDA methods can generalize over. 

Wish you the best of luck.
